name: Setup Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-terraform:
    runs-on: ubuntu-latest  # Runs on a GitHub-hosted virtual machine
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Required Dependencies
        run: |
          sudo apt update && sudo apt install -y wget unzip

      - name: Manually Add HashiCorp GPG Key
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
          sudo apt update || true  # Ignore GPG errors

      - name: Install Terraform Manually (If Repo Fails)
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/hashicorp/terraform/releases/latest | grep "tag_name" | cut -d '"' -f 4)
          wget https://releases.hashicorp.com/terraform/${LATEST_VERSION}/terraform_${LATEST_VERSION}_linux_amd64.zip
          unzip terraform_${LATEST_VERSION}_linux_amd64.zip
          sudo mv terraform /usr/local/bin/
          terraform --version
